AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway CLSI
Globals:
  Function:
    Timeout: 5
    Runtime: nodejs20.x
    MemorySize: 128
Resources:
  CLSIApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: UE2APIDESACLSIV1
      StageName: Desa
      EndpointConfiguration: REGIONAL
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldFunction
      CodeUri: s3://ilab-deploymentbucket-dev/a3d42b32ac4d7e6151647a9508d64411
      Handler: index.handler
      Policies: AWSLambdaBasicExecutionRole
      Events:
        HelloEndpoint:
          Type: Api
          Properties:
            RestApiId:
              Ref: CLSIApiGateway
            Path: /hola
            Method: GET
Outputs:
  ApiUrl:
    Description: URL del endpoint /hola
    Value:
      Fn::Sub: https://${CLSIApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Desa/hola
