service: CLSI-API-Bussines-Implement

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  timeout: 5
  memorySize: 128
  apiGateway:
    restApiId: !Ref MyApiGateway
    restApiRootResourceId: !GetAtt MyApiGateway.RootResourceId

resources: ${file(config/serverless/apigateway.yml)}
functions: ${file(config/serverless/function.cloud.yml)} 

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - owasp-data/**
    - owasp-dependency-check/**
    - .scannerwork/**
    - npm-cache/**
    - coverage/**
    - node_modules/**
